on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.32
      with:
        goos: windows
        goarch: amd64
        github_token: ${{ secrets.GITHUB_TOKEN }}
        compress_assets: OFF
    - uses: wangyoucao577/go-release-action@v1.32
      with:
        goos: linux
        goarch: amd64
        github_token: ${{ secrets.GITHUB_TOKEN }}
        compress_assets: OFF
